export enum EthnicityEnum {
  HISPANIC = 'HISPANIC',
  ASIAN = 'ASIAN',
  'NON-HISPANIC-BLACK' = 'NON-HISPANIC-BLACK',
  'NON-HISPANIC-WHITE' = 'NON-HISPANIC-WHITE',
  'NATIVE-AMERICAN' = 'NATIVE-AMERICAN',
  'PACIFIC-ISLANDER' = 'PACIFIC-ISLANDER',
  'MULTI-RACIAL' = 'MULTI-RACIAL',
  'NOT-LISTED' = 'NOT-LISTED',
}
